-- Generated by CSharp.lua Compiler
local System = System
local Attributes
System.import(function (out)
  Attributes = VoidSharpExample.ORM.Attributes
end)
System.namespace("VoidSharpExample.ORM.QueryTypes", function (namespace)
  namespace.class("DropQueryType_1", function (namespace)
    return function (T)
      local GenerateQuery, Execute, __ctor__
      __ctor__ = function (this, database)
        System.base(this).__ctor__(this, database)
      end
      GenerateQuery = function (this, type)
        local tableName = Attributes.TableAttribute.GetAttributeTable(type)
        return "DROP TABLE " .. tableName .. ";"
      end
      Execute = function (this)
        return System.async(function (async, this)
          local query = GenerateQuery(this, System.typeof(T))
          async:await(this.Database:Query(query, T))
        end, nil, this)
      end
      return {
        base = function (out)
          return {
            out.VoidSharpExample.ORM.QueryTypes.QueryType
          }
        end,
        GenerateQuery = GenerateQuery,
        Execute = Execute,
        __ctor__ = __ctor__
      }
    end
  end)
end)
