-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM.QueryTypes", function (namespace)
  namespace.class("QueryType", function (namespace)
    local __ctor__
    __ctor__ = function (this, database)
      this.Database = database
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
