-- Generated by CSharp.lua Compiler
local System = System
local VoidAccessoriesORM
System.import(function (out)
  VoidAccessoriesORM = VoidAccessories.ORM
end)
System.namespace("VoidAccessories.ORM.Serializers", function (namespace)
  namespace.class("IntegerSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      return obj:ToString()
    end
    Deserialize = function (this, obj)
      return VoidAccessoriesORM.SerializerMap.ConvertToInt(obj)
    end
    return {
      base = function (out)
        return {
          out.VoidAccessories.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
