-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpTest.Models", function (namespace)
  namespace.class("ServerNetworkData", function (namespace)
    return {
      __metadata__ = function (out)
        return {
          properties = {
            { "Color", 0x6, out.VoidSharp.Color },
            { "Name", 0x6, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
