-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  -- ReSharper disable once InconsistentNaming
  namespace.class("JSON", function (namespace)
    local Parse, Serialize
    -- <summary>
    -- Converts JSON to a Table
    -- </summary>
    Parse = function (str)
      return VoidSharp.Globals.getUtil():JSONToTable(str)
    end
    -- <summary>
    -- Converts Table to JSON
    -- </summary>
    Serialize = function (obj, prettyPrint)
      return VoidSharp.Globals.getUtil():TableToJSON(obj, prettyPrint)
    end
    return {
      Parse = Parse,
      Serialize = Serialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Parse", 0x18E, Parse, System.String, System.Object },
            { "Serialize", 0x28E, Serialize, System.Object, System.Boolean, System.String }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
