-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.Models", function (namespace)
  namespace.class("Character", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.Time = System.default(System.DateTime)
    end
    return {
      Id = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "FavoriteColor", 0x6, out.VoidSharp.Color },
            { "Id", 0x6, System.Int32, out.VoidSharpExample.ORM.Attributes.PrimaryKeyAttribute(), out.VoidSharpExample.ORM.Attributes.AutoIncrementAttribute() },
            { "Name", 0x6, System.String, out.VoidSharpExample.ORM.Attributes.ColumnLengthAttribute(100) },
            { "SteamId", 0x6, System.String, out.VoidSharpExample.ORM.Attributes.ColumnLengthAttribute(50) },
            { "Time", 0x6, System.DateTime }
          },
          class = { 0x6, System.SerializableAttribute(), out.VoidSharpExample.ORM.Attributes.TableAttribute("voidsharp_characters") }
        }
      end
    }
  end)
end)
