-- Generated by CSharp.lua Compiler
local System = System
local VoidAccessoriesLocalization
System.import(function (out)
  VoidAccessoriesLocalization = VoidAccessories.Localization
end)
System.namespace("VoidAccessories.Configuration", function (namespace)
  namespace.class("Config", function (namespace)
    local getLanguage, setLanguage, static
    static = function (this)
      setLanguage("English")
    end
    getLanguage = function ()
      return getLanguage()
    end
    setLanguage = function (value)
      VoidAccessoriesLocalization.Lang.setCurrentLanguage(value)
      setLanguage(value)
    end
    return {
      getLanguage = getLanguage,
      setLanguage = setLanguage,
      static = static,
      __metadata__ = function (out)
        return {
          properties = {
            { "Language", 0x10E, System.String, getLanguage, setLanguage }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
