-- Generated by CSharp.lua Compiler
VoidSharpTestAutoRefreshFunc()
local System = System
local VoidSharp = VoidSharp
local VoidSharpHandlers = VoidSharp.Handlers
local VoidSharpNetworking = VoidSharp.Networking
local VoidSharpTestUI
local VoidSharpTestUtilities
System.import(function (out)
  VoidSharpTestUI = VoidSharpTest.UI
  VoidSharpTestUtilities = VoidSharpTest.Utilities
end)
System.namespace("VoidSharpTest.Client", function (namespace)
  namespace.class("ClientRealm", function (namespace)
    local Main, SendUsefulData, OpenMenu
    Main = function (this)
      return System.async(function (async, this)
        VoidSharpTestUtilities.Logger.LogInfo("Clientside loaded!")

        VoidSharpHandlers.HookHandler.InitializeHooks(this)
        VoidSharpHandlers.ConCommandHandler.InitializeConCommands(this)
        VoidSharpNetworking.RPC.RegisterInstance(this)
      end, nil, this)
    end
    SendUsefulData = function (this, item)
      local player = VoidSharp.Player.LocalPlayer()
      player:ChatPrint("Got some useful data!")
      player:ChatPrint(item.PlayerName)
      player:ChatPrint(item.CreatedAt:ToString())
    end
    OpenMenu = function (this, ply, s, args, argStr)
      local panel = VoidSharpTestUI.MainPanel()
      panel:SetSize(400, 400)
      panel:MakePopup()

      panel:Center()
    end
    return {
      Main = Main,
      SendUsefulData = SendUsefulData,
      OpenMenu = OpenMenu,
      __metadata__ = function (out)
        return {
          methods = {
            { "Main", 0x86, Main, System.Task },
            { "OpenMenu", 0x406, OpenMenu, out.VoidSharp.Player, System.String, System.Array(System.String), System.String, out.VoidSharp.Handlers.ConCommandAttribute("voidsharptest_ui") },
            { "SendUsefulData", 0x106, SendUsefulData, out.VoidSharpTest.Models.InventoryItem, out.VoidSharp.Networking.RPCAttribute() }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
