-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Localization", function (namespace)
  namespace.class("LanguageDict", function (namespace)
    return {
      base = function (out)
        return {
          System.Dictionary(System.String, System.String)
        }
      end,
      __metadata__ = function (out)
        return {
          class = { 0x6 }
        }
      end
    }
  end)
end)
