-- Generated by CSharp.lua Compiler
local System = System
local VoidAccessoriesLocalization
System.import(function (out)
  VoidAccessoriesLocalization = VoidAccessories.Localization
end)
System.namespace("VoidAccessories.Localization", function (namespace)
  namespace.class("PhraseManager", function (namespace)
    local get
    get = function (this, key)
      local currLang = VoidAccessoriesLocalization.Lang.getCurrentLanguage() or "english"
      local languageDict = VoidAccessoriesLocalization.Lang.Languages:get(currLang)

      local default, phrase = languageDict:TryGetValue(key)
      if not default then
        -- Try get english
        local englishDict = VoidAccessoriesLocalization.Lang.Languages:get("english")
        local extern
        extern, phrase = englishDict:TryGetValue(key)
        if not extern then
          phrase = "Unknown"
        end
      end

      return phrase
    end
    return {
      get = get,
      __metadata__ = function (out)
        return {
          class = { 0x6 }
        }
      end
    }
  end)
end)
