-- Generated by CSharp.lua Compiler
local System = System
local DictStringObject = System.Dictionary(System.String, System.Object)
local ListDictStringObject = System.List(DictStringObject)
local VoidSharpExampleORM
System.import(function (out)
  VoidSharpExampleORM = VoidSharpExample.ORM
end)
System.namespace("VoidSharpExample.ORM", function (namespace)
  namespace.class("DatabaseResult_1", function (namespace)
    return function (T)
      local ToList, __ctor__
      local ListT = System.List(T)
      __ctor__ = function (this, result)
        this.Result = result
      end
      ToList = function (this)
        local list = ListT()
        local dict = System.cast(ListDictStringObject, this.Result)
        for _, res in System.each(dict) do
          local t = T()
          local objectMapper = VoidSharpExampleORM.ObjectMapper(t)
          objectMapper:AssignValues(res)
          list:Add(t)
        end

        return list
      end
      return {
        ToList = ToList,
        __ctor__ = __ctor__
      }
    end
  end)
end)
