-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM", function (namespace)
  -- <summary>
  -- Maps an object to a database and vice-versa.
  -- </summary>
  -- <typeparam name="T"></typeparam>
  namespace.class("DatabaseMapper_1", function (namespace)
    return function (T)
      local __ctor__
      __ctor__ = function (this, database)
        this.Database = database
      end
      return {
        __ctor__ = __ctor__
      }
    end
  end)
end)
