-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM", function (namespace)
  -- ReSharper disable once ClassNeverInstantiated.Global
  namespace.class("DatabaseConnectionResult", function (namespace)
    local __ctor__
    __ctor__ = function (this, hasFailed, error)
      this.HasFailed = hasFailed
      this.Error = error
    end
    return {
      HasFailed = false,
      __ctor__ = __ctor__
    }
  end)
end)
