-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
local VoidSharpExampleORM
System.import(function (out)
  VoidSharpExampleORM = VoidSharpExample.ORM
end)
System.namespace("VoidSharpExample.ORM", function (namespace)
  namespace.class("ObjectMapper", function (namespace)
    local GetPropertyTypes, MapValue, AssignValues, __ctor__
    __ctor__ = function (this, o)
      this.Object = o
    end
    GetPropertyTypes = function (this)
      local properties = this.Object:GetType():GetProperties()
      return Linq.ToDictionary(Linq.Select(properties, function (x)
        return System.AnonymousType({
          String = x:getName(),
          Property = x:getPropertyType()
        })
      end, System.AnonymousType), function (x)
        return x.String
      end, function (v)
        return v.Property
      end, System.String, System.Type)
    end
    MapValue = function (this, property, value)
      local serializer = VoidSharpExampleORM.SerializerMap.Serializers:get(property:getPropertyType())
      return serializer:Deserialize(value)
    end
    AssignValues = function (this, values)
      local properties = this.Object:GetType():GetProperties()
      for _, pair in System.each(values) do
        local property = Linq.FirstOrDefault(properties, function (x)
          return x:getName() == pair.Key
        end)
        if property == nil then
          System.throw(System.Exception("Object does not contain property with name " .. pair.Key .. "!"))
        end

        local value = MapValue(this, property, pair.Value)
        this.Object[pair.Key] = value
      end
    end
    return {
      GetPropertyTypes = GetPropertyTypes,
      AssignValues = AssignValues,
      __ctor__ = __ctor__
    }
  end)
end)
