-- Generated by CSharp.lua Compiler
local System = System
local VoidSharpExampleORM
local DictTypeISerializerBase
System.import(function (out)
  VoidSharpExampleORM = VoidSharpExample.ORM
  DictTypeISerializerBase = System.Dictionary(System.Type, VoidSharpExampleORM.ISerializerBase)
end)
System.namespace("VoidSharpExample.ORM", function (namespace)
  namespace.class("SerializerMap", function (namespace)
    local RegisterSerializer, ConvertToInt, class, static
    static = function (this)
      this.Serializers = DictTypeISerializerBase()
    end
    RegisterSerializer = function (TType, TSerializer)
      local t = TSerializer()
      class.Serializers:set(System.typeof(TType), t)
    end
    ConvertToInt = function (val)
      val = tonumber(val)
      return System.cast(System.Int32, val)
    end
    class = {
      RegisterSerializer = RegisterSerializer,
      ConvertToInt = ConvertToInt,
      static = static
    }
    return class
  end)
end)
