-- Generated by CSharp.lua Compiler
local System = System
local VoidAccessoriesAttributes
System.import(function (out)
  VoidAccessoriesAttributes = VoidAccessories.ORM.Attributes
end)
System.namespace("VoidAccessories.ORM.QueryTypes", function (namespace)
  namespace.class("DropQueryType_1", function (namespace)
    return function (T)
      local GenerateQuery, Execute, __ctor__
      __ctor__ = function (this, database)
        System.base(this).__ctor__(this, database)
      end
      GenerateQuery = function (this, type)
        local tableName = VoidAccessoriesAttributes.TableAttribute.GetAttributeTable(type)
        return "DROP TABLE " .. tableName .. ";"
      end
      Execute = function (this)
        return System.async(function (async, this)
          local query = GenerateQuery(this, System.typeof(T))
          async:await(this.Database:Query(query, T))
        end, nil, this)
      end
      return {
        base = function (out)
          return {
            out.VoidAccessories.ORM.QueryTypes.QueryType
          }
        end,
        GenerateQuery = GenerateQuery,
        Execute = Execute,
        __ctor__ = __ctor__,
        __metadata__ = function (out)
          return {
            methods = {
              { ".ctor", 0x106, nil, out.VoidAccessories.ORM.Database },
              { "Execute", 0x86, Execute, System.Task },
              { "GenerateQuery", 0x186, GenerateQuery, System.Type, System.String }
            },
            class = { 0x106, T }
          }
        end
      }
    end
  end)
end)
