-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
System.namespace("VoidSharpExample.ORM.Attributes", function (namespace)
  namespace.class("ColumnLengthAttribute", function (namespace)
    local GetAttributeColumnLength, class, __ctor__
    __ctor__ = function (this, columnLength)
      System.base(this).__ctor__(this)
      this._columnLength = columnLength
    end
    -- <summary>
    -- Gets the length of the column attribute.
    -- </summary>
    -- <param name="classType">A property.</param>
    -- <returns>A nullable int (null if does not have attribute)</returns>
    GetAttributeColumnLength = function (classType)
      local attributes = Linq.ToList(Linq.Where(classType:GetCustomAttributes(false), function (x)
        return x:GetType() == System.typeof(class)
      end))

      local default
      if #attributes > 0 then
        default = System.cast(class, attributes:get(0))
      else
        default = nil
      end
      local attribute = default
      local extern = attribute
      if extern ~= nil then
        extern = extern._columnLength
      end
      return extern
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      _columnLength = 0,
      GetAttributeColumnLength = GetAttributeColumnLength,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
