-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
System.namespace("VoidSharpExample.ORM.Attributes", function (namespace)
  namespace.class("PrimaryKeyAttribute", function (namespace)
    local IsPrimaryKey, class
    -- <summary>
    -- Does the property have a primary key attribute?
    -- </summary>
    -- <param name="classType">A property.</param>
    -- <returns></returns>
    IsPrimaryKey = function (classType)
      local attributes = Linq.ToList(Linq.Where(classType:GetCustomAttributes(false), function (x)
        return x:GetType() == System.typeof(class)
      end))

      local default
      if #attributes > 0 then
        default = System.cast(class, attributes:get(0))
      else
        default = nil
      end
      local attribute = default
      return attribute ~= nil
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      IsPrimaryKey = IsPrimaryKey
    }
    return class
  end)
end)
