-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM.Attributes", function (namespace)
  namespace.class("TableAttribute", function (namespace)
    local GetAttributeTable, class, __ctor__
    __ctor__ = function (this, tableName)
      System.base(this).__ctor__(this)
      this._tableName = tableName
    end
    -- <summary>
    -- Gets the table name of the table attribute.
    -- </summary>
    -- <param name="classType">A property.</param>
    -- <returns>The name of the table (if null, then <c>"voidsharpexample_" + classType.Name.ToLower()</c>)</returns>
    GetAttributeTable = function (classType)
      local tableName
      local attributes = System.Attribute.GetCustomAttributes(classType, System.typeof(class))

      local default
      if #attributes > 0 then
        default = System.cast(class, attributes:get(0))
      else
        default = nil
      end
      local attribute = default

      if attribute == nil then
        tableName = "voidsharpexample_" .. classType:getName():ToLower()
      else
        tableName = attribute._tableName
      end

      return tableName
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      GetAttributeTable = GetAttributeTable,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
