-- Generated by CSharp.lua Compiler
return function (path, loaderF)
  return System.init({
    path = path,
    files = {
      "Client.ClientRealm",
      "Configuration.Config",
      "Configuration.ConfigManager",
      "CustomSerializers.AccessoryModelBlacklistSerializer",
      "CustomSerializers.AccessorySlotsSerializer",
      "CustomSerializers.ItemPricesSerializer",
      "Extensions.StringExtensions",
      "Localization.Lang",
      "Localization.LanguageDict",
      "Localization.PhraseManager",
      "Models.AccessoryItem",
      "Models.ConfigEntry",
      "Models.EquippedAccessory",
      "Models.InventoryItem",
      "Models.VoidAccessory",
      "Objects.AccessoryModelBlacklist",
      "Objects.AccessorySlots",
      "Objects.ItemPrices",
      "Program",
      "Server.ServerRealm",
      "Utilities.Logger"
    },
    types = {
      "VoidAccessories.Client.ClientRealm",
      "VoidAccessories.Configuration.Config",
      "VoidAccessories.Configuration.ConfigManager",
      "VoidAccessories.CustomSerializers.AccessoryModelBlacklistSerializer",
      "VoidAccessories.CustomSerializers.AccessorySlotsSerializer",
      "VoidAccessories.CustomSerializers.ItemPricesSerializer",
      "VoidAccessories.Extensions.StringExtensions",
      "VoidAccessories.Localization.Lang",
      "VoidAccessories.Localization.LanguageDict",
      "VoidAccessories.Localization.PhraseManager",
      "VoidAccessories.Models.AccessoryItem",
      "VoidAccessories.Models.ConfigEntry",
      "VoidAccessories.Models.EquippedAccessory",
      "VoidAccessories.Models.InventoryItem",
      "VoidAccessories.Models.VoidAccessory",
      "VoidAccessories.Objects.AccessoryModelBlacklist",
      "VoidAccessories.Objects.AccessorySlots",
      "VoidAccessories.Objects.ItemPrices",
      "VoidAccessories.Program",
      "VoidAccessories.Server.ServerRealm",
      "VoidAccessories.Utilities.Logger"
    },
    loaderF = loaderF,
    Main = "VoidAccessories.Program.Main"
  })
end
