-- Generated by CSharp.lua Compiler
VoidAccessoriesAutoRefreshFunc()
local System = System
local VoidAccessoriesClient
local VoidAccessoriesHandlers
local VoidAccessoriesLocalization
local VoidAccessoriesNetworking
local VoidAccessoriesServer
local VoidAccessoriesUtilities
local VoidSharp
System.import(function (out)
  VoidAccessoriesClient = VoidAccessories.Client
  VoidAccessoriesHandlers = VoidAccessories.Handlers
  VoidAccessoriesLocalization = VoidAccessories.Localization
  VoidAccessoriesNetworking = VoidAccessories.Networking
  VoidAccessoriesServer = VoidAccessories.Server
  VoidAccessoriesUtilities = VoidAccessories.Utilities
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidAccessories", function (namespace)
  namespace.class("Program", function (namespace)
    local Instance, Main, HandleException, Main1, LoadRealms, HandleAutoRefresh, OnVoidLibLoad, OnLanguagesLoaded, 
    class
    Main = function (args)
      Instance = class()
      Main1(Instance):ContinueWith(function (x)
        if x:getIsFaulted() then
          HandleException(x:getException())
        end
      end)
    end
    -- <summary>
    -- Handles an exception in async threads - it's needed because we are calling an async method from a non-async method.
    -- </summary>
    -- <param name="e"></param>
    HandleException = function (e)
      local exceptionTrace = e:getMessage() .. "\n" .. e:getStackTrace() .. "\n"
      VoidAccessoriesUtilities.Logger.LogError(exceptionTrace)
    end
    Main1 = function (this)
      return System.async(function (async, this)
        VoidAccessoriesUtilities.Logger.LogInfo("VoidAccessories Loaded!")
        VoidAccessoriesHandlers.HookHandler.InitializeHooks(this)
        VoidAccessoriesNetworking.DataSerializer.RegisterSerializers()

        if VoidSharp.Globals.getVoidLib() ~= nil then
          OnVoidLibLoad(this)
        end

        async:await(LoadRealms(this))
      end, nil, this)
    end
    LoadRealms = function (this)
      return System.async(function (async, this)
        if VoidSharp.Realm.IsServer() then
          local serverRealm = VoidAccessoriesServer.ServerRealm()
          async:await(serverRealm:Main())
        elseif VoidSharp.Realm.IsClient() then
          local clientRealm = VoidAccessoriesClient.ClientRealm()
          async:await(clientRealm:Main())
        end
      end, nil, this)
    end
    -- <summary>
    -- Handles the autorefresh.
    -- </summary>
    HandleAutoRefresh = function ()
      VoidAccessoriesUtilities.Logger.LogInfo("Handling autorefresh!", "Autorefresh")

      LoadRealms(Instance):ContinueWith(function (x)
        if x:getIsFaulted() then
          HandleException(x:getException())
        end
      end)
    end
    -- <summary>
    -- Gets called after VoidLib is loaded.
    -- </summary>
    OnVoidLibLoad = function (this)
      VoidAccessoriesUtilities.Logger.LogInfo("VoidLib successfully loaded!")

      if VoidSharp.Realm.IsServer() then
        VoidSharp.VoidLib.RegisterAddon("VoidAccessories", 0, "{{ DEV_LICENSE }}")
      end
    end
    -- <summary>
    -- Gets called after the VoidAccessories languages are loaded.
    -- </summary>
    OnLanguagesLoaded = function (this)
      VoidAccessoriesLocalization.Lang.LoadLanguages("VoidAccessories")
      VoidAccessoriesUtilities.Logger.LogInfo("Loaded " .. VoidAccessoriesLocalization.Lang.Languages:getCount() .. " languages!", "Languages")
    end
    class = {
      Main = Main,
      HandleAutoRefresh = HandleAutoRefresh,
      OnVoidLibLoad = OnVoidLibLoad,
      OnLanguagesLoaded = OnLanguagesLoaded,
      __metadata__ = function (out)
        return {
          properties = {
            { "Instance", 0x9, class }
          },
          methods = {
            { "HandleAutoRefresh", 0xE, HandleAutoRefresh },
            { "HandleException", 0x109, HandleException, System.Exception },
            { "LoadRealms", 0x81, LoadRealms, System.Task },
            { "Main", 0x10E, Main, System.Array(System.String) },
            { "Main", 0x81, Main1, System.Task },
            { "OnLanguagesLoaded", 0x6, OnLanguagesLoaded, out.VoidAccessories.Handlers.HookAttribute("VoidAccessories.Lang.LanguagesLoaded", nil) },
            { "OnVoidLibLoad", 0x6, OnVoidLibLoad, out.VoidAccessories.Handlers.HookAttribute("VoidLib.Loaded", nil) }
          },
          class = { 0x4 }
        }
      end
    }
    return class
  end)
end)
