-- Generated by CSharp.lua Compiler
local System = System
local SystemGlobalization = System.Globalization
local VoidSharpExampleORM
System.import(function (out)
  VoidSharpExampleORM = VoidSharpExample.ORM
end)
System.namespace("VoidSharpExample.ORM.Serializers", function (namespace)
  namespace.class("DateTimeSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      local time = System.cast(System.DateTime, obj)
      return time:Subtract(System.DateTime(1970, 1, 1)):getTotalSeconds():ToString(SystemGlobalization.CultureInfo.getInvariantCulture())
    end
    Deserialize = function (this, obj)
      local timestamp = VoidSharpExampleORM.SerializerMap.ConvertToInt(obj)
      return System.DateTime(1970, 1, 1):AddSeconds(timestamp)
    end
    return {
      base = function (out)
        return {
          out.VoidSharpExample.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize
    }
  end)
end)
