-- Generated by CSharp.lua Compiler
local System = System
local VoidSharpExampleORM
System.import(function (out)
  VoidSharpExampleORM = VoidSharpExample.ORM
end)
System.namespace("VoidSharpExample.ORM.Serializers", function (namespace)
  namespace.class("IntegerSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      return obj:ToString()
    end
    Deserialize = function (this, obj)
      return VoidSharpExampleORM.SerializerMap.ConvertToInt(obj)
    end
    return {
      base = function (out)
        return {
          out.VoidSharpExample.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize
    }
  end)
end)
