-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM.Serializers", function (namespace)
  namespace.class("StringSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      local str = driver:Escape(System.cast(System.String, obj), true)

      return "'" .. str .. "'"
    end
    Deserialize = function (this, obj)
      return obj
    end
    return {
      base = function (out)
        return {
          out.VoidSharpExample.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize
    }
  end)
end)
