-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("AccessoryShopItem", function (namespace)
    return {
      AccessoryKey = 0,
      __metadata__ = function (out)
        return {
          properties = {
            { "AccessoryKey", 0x6, System.Int32, out.VoidAccessories.ORM.Attributes.PrimaryKeyAttribute() },
            { "Description", 0x6, System.String },
            { "Name", 0x6, System.String },
            { "Prices", 0x6, out.VoidAccessories.Objects.ItemPrices }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
