-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("AccessoryItem", function (namespace)
    return {
      Id = 0,
      AllowClientOffsetEdit = false,
      AccessoryType = 0,
      SellInShop = false,
      __metadata__ = function (out)
        return {
          properties = {
            { "AccessoryKey", 0x6, System.String },
            { "AccessoryType", 0x6, System.Int32 },
            { "AllowClientOffsetEdit", 0x6, System.Boolean },
            { "Blacklist", 0x6, out.VoidAccessories.Objects.AccessoryModelBlacklist },
            { "Description", 0x6, System.String },
            { "Id", 0x6, System.Int32, out.VoidSharp.ORM.Attributes.PrimaryKeyAttribute(), out.VoidSharp.ORM.Attributes.AutoIncrementAttribute() },
            { "Name", 0x6, System.String },
            { "Prices", 0x6, out.VoidAccessories.Objects.ItemPrices },
            { "SellInShop", 0x6, System.Boolean },
            { "Slots", 0x6, out.VoidAccessories.Objects.AccessorySlots }
          },
          class = { 0x6, out.VoidSharp.ORM.Attributes.TableAttribute("voidaccessories_items") }
        }
      end
    }
  end)
end)
