-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("ConfigEntry", function (namespace)
    return {
      __metadata__ = function (out)
        return {
          properties = {
            { "Key", 0x6, System.String, out.VoidAccessories.ORM.Attributes.PrimaryKeyAttribute(), out.VoidAccessories.ORM.Attributes.ColumnLengthAttribute(50) },
            { "Value", 0x6, System.Object }
          },
          class = { 0x6, System.SerializableAttribute(), out.VoidAccessories.ORM.Attributes.TableAttribute("voidaccessories_config") }
        }
      end
    }
  end)
end)
