-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("EquippedAccessory", function (namespace)
    return {
      AccessoryKey = 0,
      __metadata__ = function (out)
        return {
          properties = {
            { "AccessoryKey", 0x6, System.Int32 },
            { "SteamId64", 0x6, System.String, out.VoidSharp.ORM.Attributes.PrimaryKeyAttribute() }
          },
          class = { 0x6, out.VoidSharp.ORM.Attributes.TableAttribute("voidaccessories_equippedaccessories") }
        }
      end
    }
  end)
end)
