-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("InventoryItem", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.PurchasedAt = System.default(System.DateTime)
      this.ExpireTime = System.default(System.DateTime)
    end
    return {
      ItemId = 0,
      IsTemporary = false,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "ExpireTime", 0x6, System.DateTime },
            { "IsTemporary", 0x6, System.Boolean },
            { "ItemId", 0x6, System.Int32, out.VoidAccessories.ORM.Attributes.PrimaryKeyAttribute() },
            { "PurchasedAt", 0x6, System.DateTime },
            { "SteamId64", 0x6, System.String, out.VoidAccessories.ORM.Attributes.PrimaryKeyAttribute() }
          },
          class = { 0x6, out.VoidAccessories.ORM.Attributes.TableAttribute("voidaccessories_inventories") }
        }
      end
    }
  end)
end)
