-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("MigrationVersion", function (namespace)
    return {
      Version = 0,
      TimesUpdated = 0,
      __metadata__ = function (out)
        return {
          properties = {
            { "Id", 0x6, System.String, out.VoidAccessories.ORM.Attributes.PrimaryKeyAttribute() },
            { "TimesUpdated", 0x6, System.Int32 },
            { "Version", 0x6, System.Int32 }
          },
          class = { 0x6, System.SerializableAttribute(), out.VoidAccessories.ORM.Attributes.TableAttribute("voidaccessories_migrationversion") }
        }
      end
    }
  end)
end)
