-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Models", function (namespace)
  namespace.class("VoidAccessory", function (namespace)
    return {
      WorkshopId = 0,
      TranslateX = 0,
      TranslateY = 0,
      TranslateZ = 0,
      RotateX = 0,
      RotateY = 0,
      RotateZ = 0,
      ScaleX = 0,
      ScaleY = 0,
      ScaleZ = 0,
      __metadata__ = function (out)
        return {
          properties = {
            { "Bone", 0x6, System.String },
            { "Id", 0x6, System.String, out.VoidAccessories.ORM.Attributes.PrimaryKeyAttribute() },
            { "Model", 0x6, System.String },
            { "RotateX", 0x6, System.Int32 },
            { "RotateY", 0x6, System.Int32 },
            { "RotateZ", 0x6, System.Int32 },
            { "ScaleX", 0x6, System.Int32 },
            { "ScaleY", 0x6, System.Int32 },
            { "ScaleZ", 0x6, System.Int32 },
            { "TranslateX", 0x6, System.Int32 },
            { "TranslateY", 0x6, System.Int32 },
            { "TranslateZ", 0x6, System.Int32 },
            { "WorkshopId", 0x6, System.Int32 }
          },
          class = { 0x6, out.VoidAccessories.ORM.Attributes.TableAttribute("voidaccessories_accessories") }
        }
      end
    }
  end)
end)
