-- Generated by CSharp.lua Compiler
return function (path, loaderF)
  return System.init({
    path = path,
    files = {
      "Client.ClientRealm",
      "Models.InventoryItem",
      "Models.NetworkData",
      "Program",
      "Server.ServerRealm",
      "UI.MainPanel",
      "Utilities.Logger"
    },
    types = {
      "VoidSharpTest.Client.ClientRealm",
      "VoidSharpTest.Models.InventoryItem",
      "VoidSharpTest.Models.ServerNetworkData",
      "VoidSharpTest.Program",
      "VoidSharpTest.Server.ServerRealm",
      "VoidSharpTest.UI.MainPanel",
      "VoidSharpTest.Utilities.Logger"
    },
    loaderF = loaderF,
    Main = "VoidSharpTest.Program.Main"
  })
end
