-- Generated by CSharp.lua Compiler
VoidAccessoriesAutoRefreshFunc()
local System = System
local VoidAccessoriesConfiguration
local VoidAccessoriesMigrations
local VoidAccessoriesORM
local VoidSharp
System.import(function (out)
  VoidAccessoriesConfiguration = VoidAccessories.Configuration
  VoidAccessoriesMigrations = VoidAccessories.Migrations
  VoidAccessoriesORM = VoidAccessories.ORM
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidAccessories.Server", function (namespace)
  namespace.class("ServerRealm", function (namespace)
    local Main, DatabaseTasks
    Main = function (this)
      return System.async(function (async, this)
        async:await(DatabaseTasks(this))
        async:await(VoidAccessoriesConfiguration.ConfigManager.CreateEntries(this.Database))
      end, nil, this)
    end
    DatabaseTasks = function (this)
      return System.async(function (async, this)
        this.Database = VoidAccessoriesORM.Database(VoidSharp.SQLite())
        async:await(this.Database:Connect())

        -- Handle migrations
        local migrationManager = VoidAccessoriesMigrations.MigrationManager()
        async:await(migrationManager:UpdateMigrations(this.Database))
      end, nil, this)
    end
    return {
      Main = Main,
      __metadata__ = function (out)
        return {
          properties = {
            { "Database", 0x1, out.VoidAccessories.ORM.Database }
          },
          methods = {
            { "DatabaseTasks", 0x81, DatabaseTasks, System.Task },
            { "Main", 0x86, Main, System.Task }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
