-- Generated by CSharp.lua Compiler
local System = System
local VoidAccessoriesObjects
local VoidSharp
local ListInt32
System.import(function (out)
  VoidAccessoriesObjects = VoidAccessories.Objects
  VoidSharp = out.VoidSharp
  ListInt32 = System.List(System.Int32)
end)
System.namespace("VoidAccessories.CustomSerializers", function (namespace)
  namespace.class("AccessorySlotsSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, databaseDriver)
      local slots = System.cast(VoidAccessoriesObjects.AccessorySlots, obj)
      return "'" .. VoidSharp.JSON.Serialize(slots.Slots, false) .. "'"
    end
    Deserialize = function (this, obj)
      local str = System.cast(System.String, obj)
      local tbl = VoidSharp.JSON.Parse(str)

      return VoidSharp.JSON.TableToList(tbl, ListInt32)
    end
    return {
      base = function (out)
        return {
          out.VoidAccessories.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
