-- Generated by CSharp.lua Compiler
local System = System
local DictStringInt32 = System.Dictionary(System.String, System.Int32)
local VoidAccessoriesObjects
local VoidSharp
System.import(function (out)
  VoidAccessoriesObjects = VoidAccessories.Objects
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidAccessories.CustomSerializers", function (namespace)
  namespace.class("ItemPricesSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, databaseDriver)
      local itemPrices = System.cast(VoidAccessoriesObjects.ItemPrices, obj)
      return "'" .. VoidSharp.JSON.Serialize(itemPrices.PriceDict, false) .. "'"
    end
    Deserialize = function (this, obj)
      local str = System.cast(System.String, obj)
      local tbl = VoidSharp.JSON.Parse(str)

      return VoidSharp.JSON.TableToDictionary(tbl, DictStringInt32)
    end
    return {
      base = function (out)
        return {
          out.VoidAccessories.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
