-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM.Specifiers", function (namespace)
  namespace.class("AlterSpecifier", function (namespace)
    local getName, getDataType, __ctor__
    __ctor__ = function (this, a, b)
      local insertTuple = System.Tuple(a, b)
      this.Alter = insertTuple
    end
    getName = function (this)
      return this.Alter[1]
    end
    getDataType = function (this)
      return this.Alter[2]
    end
    return {
      getName = getName,
      getDataType = getDataType,
      __ctor__ = __ctor__
    }
  end)
end)
