-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM.Specifiers", function (namespace)
  namespace.class("InsertSpecifier", function (namespace)
    local getKey, getValue, __ctor__
    __ctor__ = function (this, a, b)
      local insertTuple = System.Tuple(a, b)
      this.Insert = insertTuple
    end
    getKey = function (this)
      return this.Insert[1]
    end
    getValue = function (this)
      return this.Insert[2]
    end
    return {
      getKey = getKey,
      getValue = getValue,
      __ctor__ = __ctor__
    }
  end)
end)
