-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharpExample.ORM.Specifiers", function (namespace)
  namespace.class("WhereSpecifier", function (namespace)
    local getKey, getComparator, getValue, __ctor__
    __ctor__ = function (this, a, comparator, b)
      local whereTuple = System.Tuple(a, comparator, b)
      this.Where = whereTuple
    end
    getKey = function (this)
      return this.Where[1]
    end
    getComparator = function (this)
      return this.Where[2]
    end
    getValue = function (this)
      return this.Where[3]
    end
    return {
      getKey = getKey,
      getComparator = getComparator,
      getValue = getValue,
      __ctor__ = __ctor__
    }
  end)
end)
