-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp", function (namespace)
  namespace.class("Globals", function (namespace)
    local ConsoleLog, AddConCommand, Error
    ConsoleLog = function (args)
      MsgC(unpack(args))
    end
    AddConCommand = function (name, callback, autoComplete, helpText, flags)
      concommand.Add(name, callback, autoComplete, helpText, flags)
    end
    Error = function (err)
      error(err)
    end
    return {
      ConsoleLog = ConsoleLog,
      AddConCommand = AddConCommand,
      Error = Error
    }
  end)
end)
