-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp", function (namespace)
  -- ReSharper disable once InconsistentNaming
  namespace.class("JSON", function (namespace)
    local Parse, Serialize
    -- <summary>
    -- </summary>
    Parse = function (str)
      System.throw(System.NotImplementedException())
    end
    -- <summary>
    -- </summary>
    Serialize = function (obj)
      System.throw(System.NotImplementedException())
    end
    return {
      Parse = Parse,
      Serialize = Serialize
    }
  end)
end)
