-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp", function (namespace)
  namespace.class("Net", function (namespace)
    local AddNetworkString, Start, Send, Send1, Broadcast, WriteString, ReadString, Receive, 
    Receive1
    -- <summary>
    -- </summary>
    AddNetworkString = function (str)
    end
    -- <summary>
    -- </summary>
    Start = function (msg)
    end
    -- <summary>
    -- </summary>
    Send = function (player)
    end
    -- <summary>
    -- </summary>
    Send1 = function (players)
    end
    -- <summary>
    -- </summary>
    Broadcast = function ()
    end
    -- <summary>
    -- </summary>
    WriteString = function (str)
      System.throw(System.NotImplementedException())
    end
    -- <summary>
    -- </summary>
    ReadString = function ()
      System.throw(System.NotImplementedException())
    end
    Receive = function (id, action)
      net.Receive(id, action)
    end
    Receive1 = function (id, action)
      net.Receive(id, action)
    end
    return {
      AddNetworkString = AddNetworkString,
      Start = Start,
      Send = Send,
      Send1 = Send1,
      Broadcast = Broadcast,
      WriteString = WriteString,
      ReadString = ReadString,
      Receive = Receive,
      Receive1 = Receive1
    }
  end)
end)
