-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Panel", function (namespace)
    local Add, SetSize, Center, MakePopup, __ctor__
    __ctor__ = function (this, name)
      this.VGUIPanel = VoidSharp.VGUI.Create(name)
    end
    Add = function (this, panel)
      this.VGUIPanel:Add(panel)
    end
    SetSize = function (this, w, h)
      this.VGUIPanel:SetSize(w, h)
    end
    Center = function (this)
      this.VGUIPanel:Center()
    end
    MakePopup = function (this)
      this.VGUIPanel:MakePopup()
    end
    return {
      Add = Add,
      SetSize = SetSize,
      Center = Center,
      MakePopup = MakePopup,
      __ctor__ = __ctor__
    }
  end)
end)
