-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
local ListTeam
System.import(function (out)
  VoidSharp = out.VoidSharp
  ListTeam = System.List(VoidSharp.Team)
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Team", function (namespace)
    local getName, getColor, getClass, getPlayers, getSpawnPoint, getSpawnPoints, getPlayerCount, GetName, 
    GetAllTeams, NumPlayers, GetSpawnPoint, GetSpawnPoints, GetClass, GetPlayers, GetColor, __ctor__
    __ctor__ = function (this, index)
      this.Index = index
    end
    getName = function (this)
      return team.GetName(this.Index)
    end
    getColor = function (this)
      return GetColor(this.Index)
    end
    getClass = function (this)
      return team.GetClass(this.Index)
    end
    getPlayers = function (this)
      return team.GetPlayers(this.Index)
    end
    getSpawnPoint = function (this)
      return team.GetSpawnPoint(this.Index)
    end
    getSpawnPoints = function (this)
      return team.GetSpawnPoints(this.Index)
    end
    getPlayerCount = function (this)
      return team.NumPlayers(this.Index)
    end
    -- <summary>
    -- </summary>
    GetName = function (teamIndex)
      System.throw(System.NotImplementedException())
    end
    GetAllTeams = function ()
      local returnVal = ListTeam()
      local teams = team.GetAllTeams()
      for k, v in ipairs(teams) do
          returnVal:Add(VoidSharp.Team(k))
      end

      return returnVal
    end
    -- <summary>
    -- </summary>
    NumPlayers = function (teamIndex)
      System.throw(System.NotImplementedException())
    end
    -- <summary>
    -- </summary>
    GetSpawnPoint = function (teamIndex)
      System.throw(System.NotImplementedException())
    end
    -- <summary>
    -- </summary>
    GetSpawnPoints = function (teamIndex)
      System.throw(System.NotImplementedException())
    end
    -- <summary>
    -- </summary>
    GetClass = function (teamIndex)
      System.throw(System.NotImplementedException())
    end
    -- <summary>
    -- </summary>
    GetPlayers = function (teamIndex)
      System.throw(System.NotImplementedException())
    end
    GetColor = function (teamIndex)
      local r = 0
      local g = 0
      local b = 0
      local a = 0
      local col = team.GetColor(teamIndex)
      r = col.r
      g = col.g
      b = col.b
      a = col.a

      return VoidSharp.Color(r, g, b, a)
    end
    return {
      Index = 0,
      getName = getName,
      getColor = getColor,
      getClass = getClass,
      getPlayers = getPlayers,
      getSpawnPoint = getSpawnPoint,
      getSpawnPoints = getSpawnPoints,
      getPlayerCount = getPlayerCount,
      GetAllTeams = GetAllTeams,
      __ctor__ = __ctor__
    }
  end)
end)
