-- Generated by CSharp.lua Compiler
local System = System
local ArrayObject = System.Array(System.Object)
local VoidAccessoriesHandlers
local VoidSharp
System.import(function (out)
  VoidAccessoriesHandlers = VoidAccessories.Handlers
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidAccessories.Handlers", function (namespace)
  namespace.class("ConCommandHandler", function (namespace)
    local InitializeConCommands
    -- <summary>
    -- Initializes concommands for usage in passed instance.
    -- </summary>
    -- <param name="instance">The instance of the class.</param>
    InitializeConCommands = function (instance)
      local methods = VoidAccessoriesHandlers.ConCommandAttribute.GetAllConCommandAttributes(instance:GetType())
      for _, method in System.each(methods) do
        local hookAttribute = System.cast(VoidAccessoriesHandlers.ConCommandAttribute, method:GetCustomAttributes(System.typeof(VoidAccessoriesHandlers.ConCommandAttribute), true):get(0))

        local name = hookAttribute.Name

        VoidSharp.Globals.AddConCommand(name, function (player, s, arg3, arg4)
          method:Invoke(instance, ArrayObject(player, s, arg3, arg4))
        end, nil, nil, 0)
      end
    end
    return {
      InitializeConCommands = InitializeConCommands,
      __metadata__ = function (out)
        return {
          methods = {
            { "InitializeConCommands", 0x10E, InitializeConCommands, System.Object }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
