-- Generated by CSharp.lua Compiler
VoidSharpTestAutoRefreshFunc()
local System = System
local VoidSharpDerma = VoidSharp.Derma
local VoidSharpNetworking = VoidSharp.Networking
local VoidSharpTestModels
System.import(function (out)
  VoidSharpTestModels = VoidSharpTest.Models
end)
System.namespace("VoidSharpTest.UI", function (namespace)
  namespace.class("MainPanel", function (namespace)
    local SendDataToServer, __ctor__
    __ctor__ = function (this)
      System.base(this).__ctor__(this)
      this:setTitle("VoidSharp TEST")

      local textEntry = this:Add("DTextEntry"):Cast(VoidSharpDerma.TextEntry)
      textEntry:Dock(4 --[[DockType.Top]])
      textEntry:DockMargin(50, 50, 50, 10)
      textEntry:setHeight(40)

      textEntry:setUpdateOnType(true)

      textEntry:OnValueChange(function (self, str)
        this:setTitle(str)
      end)

      local mixer = this:Add("DColorMixer"):Cast(VoidSharpDerma.ColorMixer)
      mixer:Dock(4 --[[DockType.Top]])
      mixer:DockMargin(50, 10, 50, 10)
      mixer:setHeight(150)

      local button = this:Add("DButton"):Cast(VoidSharpDerma.Button)
      button:Dock(4 --[[DockType.Top]])
      button:DockMargin(100, 20, 100, 40)
      button:setHeight(40)
      button:setText("Click me!!")

      button:DoClick(function ()
        button:setText("Data sent to server!")

        SendDataToServer(this, textEntry:getValue(), mixer:getColor())
      end)
    end
    SendDataToServer = function (this, name, color)
      local default = VoidSharpTestModels.ServerNetworkData()
      default.Color = color
      default.Name = name
      local data = default

      VoidSharpNetworking.RPC.Send("SendDataToServer", data, VoidSharpTestModels.ServerNetworkData)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Derma.Frame
        }
      end,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "SendDataToServer", 0x201, SendDataToServer, System.String, out.VoidSharp.Color }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
