-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Networking.Serializers", function (namespace)
  namespace.class("StringSerializer", function (namespace)
    local Write, Read
    Write = function (this, writer, val)
      net.WriteString(System.cast(System.String, val))
    end
    Read = function (this, reader)
      return net.ReadString()
    end
    return {
      base = function (out)
        return {
          out.VoidAccessories.Networking.INetworkSerializer
        }
      end,
      Write = Write,
      Read = Read,
      __metadata__ = function (out)
        return {
          methods = {
            { "Read", 0x186, Read, out.VoidAccessories.Networking.NetworkReader, System.Object },
            { "Write", 0x206, Write, out.VoidAccessories.Networking.NetworkWriter, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
