-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Objects", function (namespace)
  namespace.class("AccessorySlots", function (namespace)
    local __ctor__
    __ctor__ = function (this, slots)
      this.Slots = slots
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Slots", 0x6, System.List(System.Int32) }
          },
          methods = {
            { ".ctor", 0x106, nil, System.List(System.Int32) }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
