-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Objects", function (namespace)
  namespace.class("AccessoryModelBlacklist", function (namespace)
    local __ctor__
    __ctor__ = function (this, blacklist)
      this.Blacklist = blacklist
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Blacklist", 0x6, System.List(System.String) }
          },
          methods = {
            { ".ctor", 0x106, nil, System.List(System.String) }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
