-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidAccessories.Objects", function (namespace)
  namespace.class("ItemPrices", function (namespace)
    local AddPrice, GetPrice, __ctor__
    __ctor__ = function (this, dict)
      this.PriceDict = dict
    end
    AddPrice = function (this, currency, price)
      this.PriceDict:AddKeyValue(currency, price)
    end
    GetPrice = function (this, currency)
      return this.PriceDict:get(currency)
    end
    return {
      AddPrice = AddPrice,
      GetPrice = GetPrice,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "PriceDict", 0x6, System.Dictionary(System.String, System.Int32) }
          },
          methods = {
            { ".ctor", 0x106, nil, System.Dictionary(System.String, System.Int32) },
            { "AddPrice", 0x206, AddPrice, System.String, System.Int32 },
            { "GetPrice", 0x186, GetPrice, System.String, System.Int32 }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
